----------------------------------------------------
-- you should do "python manage.py migrate" first
----------------------------------------------------

CREATE TABLE "Province" (
    province_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE "City" (
    city_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    province_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT FK_City_Province FOREIGN KEY (province_id)
        REFERENCES "Province"(province_id)
        ON DELETE CASCADE
);

CREATE TABLE "Address" (
    address_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_id INT NOT NULL,
    neighborhood VARCHAR(200) NULL,
    CONSTRAINT FK_Address_City FOREIGN KEY (city_id)
        REFERENCES "City"(city_id)
        ON DELETE CASCADE
);

CREATE INDEX IX_Address_CityID ON "Address" (city_id);

CREATE TABLE "Brand" (
    brand_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    country VARCHAR(50) NULL
);

CREATE TABLE "Model" (
    model_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    brand_id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(20) NOT NULL DEFAULT 'car',
    CONSTRAINT FK_Model_Brand FOREIGN KEY (brand_id)
        REFERENCES "Brand"(brand_id)
        ON DELETE CASCADE
);

CREATE TABLE "Vehicle" (
    vehicle_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model_id INT NOT NULL,
    production_year INT NULL,
    color_out VARCHAR(50) NOT NULL,
    color_in VARCHAR(50) NULL,
    transmission_type VARCHAR(50) NULL,
    fuel_type VARCHAR(50) NOT NULL,
    consumption NUMERIC(5,2) NULL,
    CONSTRAINT FK_Vehicle_Model FOREIGN KEY (model_id)
        REFERENCES "Model"(model_id)
        ON DELETE CASCADE
);

CREATE INDEX IX_Vehicle_ModelID ON "Vehicle" (model_id);
CREATE INDEX IX_Vehicle_ProductionYear ON "Vehicle" (production_year);

CREATE TABLE "Car" (
    vehicle_id INT PRIMARY KEY,
    body_type VARCHAR(50) NULL,
    engine VARCHAR(100) NULL,
    cylinder_volume INT NULL,
    enginepower INT NULL,
    torque INT NULL,
    accelerate NUMERIC(4,2) NULL,
    CONSTRAINT FK_Car_Vehicle FOREIGN KEY (vehicle_id)
        REFERENCES "Vehicle"(vehicle_id)
        ON DELETE CASCADE
);

CREATE INDEX IX_Car_BodyType ON "Car" (body_type);

CREATE TABLE "Motorcycle" (
    vehicle_id INT PRIMARY KEY,
    class VARCHAR(50) NULL,
    engine VARCHAR(100) NULL,
    engine_cc INT NULL,
    gearbox VARCHAR(50) NULL,
    weight INT NULL,
    CONSTRAINT FK_Motorcycle_Vehicle FOREIGN KEY (vehicle_id)
        REFERENCES "Vehicle"(vehicle_id)
        ON DELETE CASCADE
);

CREATE TABLE "HeavyVehicle" (
    vehicle_id INT PRIMARY KEY,
    heavy_type VARCHAR(50) NULL,
    "usage" VARCHAR(100) NULL,
    CONSTRAINT FK_HeavyVehicle_Vehicle FOREIGN KEY (vehicle_id)
        REFERENCES "Vehicle"(vehicle_id)
        ON DELETE CASCADE
);

CREATE TABLE "User" (
    userid INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    phone VARCHAR(20) NOT NULL,
    reg_status BOOLEAN DEFAULT FALSE,
    account_status BOOLEAN DEFAULT TRUE,
    register_date TIMESTAMP NULL,
    national_id VARCHAR(10) NULL,
    username VARCHAR(50) NULL,
    user_auth_id INT NULL,
    address_id INT NULL,

    CONSTRAINT UQ_User_Phone UNIQUE (phone),
    CONSTRAINT UQ_User_Username UNIQUE (username),

    CONSTRAINT CHK_User_NationalID CHECK (
        national_id IS NULL OR (national_id ~ '^[0-9]{10}$')
    ),

    CONSTRAINT FK_User_Address FOREIGN KEY (address_id)
        REFERENCES "Address"(address_id),
    CONSTRAINT FK_User_AuthUser FOREIGN KEY (user_auth_id)
        REFERENCES auth_user(id)
);

CREATE TABLE "Advertisement" (
    ad_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    vehicle_id INT NOT NULL,
    userid INT NOT NULL,
    address_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    sell_type VARCHAR(60) NOT NULL,
    price NUMERIC(18,0) NULL,
    descriptions TEXT NULL,
    published BOOLEAN DEFAULT TRUE,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_date TIMESTAMP NULL,
    ad_type VARCHAR(50) NULL,
    car_condition VARCHAR(50) NULL,
    km_age INT NULL,
    body_status VARCHAR(50) NULL,
    free_zone BOOLEAN DEFAULT FALSE,
    active_status BOOLEAN DEFAULT TRUE,

    CONSTRAINT FK_Advertisement_Vehicle FOREIGN KEY (vehicle_id)
        REFERENCES "Vehicle"(vehicle_id) ON DELETE CASCADE,
    CONSTRAINT FK_Advertisement_User FOREIGN KEY (userid)
        REFERENCES "User"(userid) ON DELETE CASCADE,
    CONSTRAINT FK_Advertisement_Address FOREIGN KEY (address_id)
        REFERENCES "Address"(address_id) ON DELETE CASCADE,

    CONSTRAINT CHK_Advertisement_SellType CHECK (
        sell_type IN ('نقدی', 'اقساطی', 'توافقی', 'حواله')
    ),
    CONSTRAINT CHK_Advertisement_CarCondition CHECK (
        car_condition IS NULL OR car_condition IN ('صفر', 'کارکرده')
    )
);

CREATE INDEX IX_Advertisement_UserID ON "Advertisement" (userid);
CREATE INDEX IX_Advertisement_AddressID ON "Advertisement" (address_id);
CREATE INDEX IX_Advertisement_CarCondition ON "Advertisement" (car_condition);
CREATE INDEX IX_Advertisement_Price ON "Advertisement" (price);
CREATE INDEX IX_Advertisement_BodyStatus ON "Advertisement" (body_status);

CREATE TABLE "Image" (
    image_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ad_id INT NOT NULL,
    url VARCHAR(500) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Image_Advertisement FOREIGN KEY (ad_id)
        REFERENCES "Advertisement"(ad_id)
        ON DELETE CASCADE
);

CREATE TABLE "Video" (
    video_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ad_id INT NOT NULL,
    url VARCHAR(500) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_Video_Advertisement FOREIGN KEY (ad_id)
        REFERENCES "Advertisement"(ad_id)
        ON DELETE CASCADE
);

CREATE TABLE "Instalment" (
    ad_id INT PRIMARY KEY,
    first_payment NUMERIC(18,0) NOT NULL,
    second_payment NUMERIC(18,0) NULL,
    payment_per_instalment NUMERIC(18,0) NOT NULL,
    payment_count INT NOT NULL,
    payment_period VARCHAR(50) NOT NULL,
    delivery_date VARCHAR(100) NULL,
    CONSTRAINT FK_Instalment_Advertisement FOREIGN KEY (ad_id)
        REFERENCES "Advertisement"(ad_id)
        ON DELETE CASCADE
);

CREATE TABLE "Remittance" (
    remittance_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ad_id INT NOT NULL UNIQUE,
    deposit_amount NUMERIC(18,0) NOT NULL,
    final_price NUMERIC(18,0) NOT NULL,
    delivery_time VARCHAR(50) NOT NULL,
    CONSTRAINT FK_Remittance_Advertisement
        FOREIGN KEY (ad_id)
        REFERENCES "Advertisement"(ad_id)
        ON DELETE CASCADE
);

CREATE INDEX IX_Remittance_FinalPrice ON "Remittance"(final_price);

CREATE TABLE "Favorite" (
    favorite_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid INT NOT NULL,
    ad_id INT NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT FK_Favorite_User
        FOREIGN KEY (userid)
        REFERENCES "User"(userid),
    CONSTRAINT FK_Favorite_Advertisement
        FOREIGN KEY (ad_id)
        REFERENCES "Advertisement"(ad_id)
        ON DELETE CASCADE,
    CONSTRAINT UQ_Favorite_User_Advertisement
        UNIQUE (userid, ad_id)
);

CREATE INDEX IX_Favorite_UserID ON "Favorite"(userid);
CREATE INDEX IX_Favorite_AdvertisementID ON "Favorite"(ad_id);

CREATE TABLE "ContactMessages" (
    contact_message_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(254) NOT NULL,
    subject VARCHAR(30) NOT NULL CHECK (subject IN ('support', 'ad', 'cooperation', 'other')),
    message TEXT NOT NULL,
    created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IX_ContactMessages_IsRead ON "ContactMessages" (is_read);
CREATE INDEX IX_ContactMessages_CreatedDate ON "ContactMessages" (created_date);