# Generated by Django 5.2.6 on 2026-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('reg_status', models.BooleanField(default=False)),
                ('account_status', models.BooleanField(default=True)),
                ('register_date', models.DateTimeField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=10, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
                'managed': False,
            },
        ),
    ]
