# Generated by Django 5.2.6 on 2026-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessages',
            fields=[
                ('contact_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('support', 'پشتیبانی فنی'), ('ad', 'مشکل در آگهی'), ('cooperation', 'همکاری و تبلیغات'), ('other', 'سایر موارد')], default='other', max_length=30)),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ContactMessages',
                'managed': False,
            },
        ),
    ]
