# Generated by Django 5.2.6 on 2026-08-09 07:56

import advertisements.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('sell_type', models.CharField(max_length=60)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('ad_type', models.CharField(blank=True, max_length=50, null=True)),
                ('car_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('km_age', models.IntegerField(blank=True, null=True)),
                ('body_status', models.CharField(blank=True, max_length=50, null=True)),
                ('free_zone', models.BooleanField(default=False)),
                ('active_status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Advertisement',
                'ordering': ['-created_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('favorite_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Favorite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(db_column='url', max_length=500, upload_to=advertisements.models.advertisement_image_upload_path)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('remittance_id', models.AutoField(primary_key=True, serialize=False)),
                ('deposit_amount', models.DecimalField(decimal_places=0, max_digits=18)),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=18)),
                ('delivery_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Remittance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instalment',
            fields=[
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='instalment', serialize=False, to='advertisements.advertisement')),
                ('first_payment', models.DecimalField(decimal_places=0, max_digits=18)),
                ('second_payment', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('payment_per_instalment', models.DecimalField(decimal_places=0, max_digits=18)),
                ('payment_count', models.IntegerField()),
                ('payment_period', models.CharField(max_length=50)),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Instalment',
                'managed': False,
            },
        ),
    ]
