# Generated by Django 5.2.6 on 2026-08-09 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Brand',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('color_out', models.CharField(max_length=50)),
                ('color_in', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(max_length=50)),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Model',
                'ordering': ['brand', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='car', serialize=False, to='vehicles.vehicle')),
                ('body_type', models.CharField(max_length=50)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('cylinder_volume', models.IntegerField(blank=True, null=True)),
                ('enginepower', models.IntegerField(blank=True, null=True)),
                ('torque', models.IntegerField(blank=True, null=True)),
                ('accelerate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'Car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HeavyVehicle',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='heavy_vehicle', serialize=False, to='vehicles.vehicle')),
                ('heavy_type', models.CharField(max_length=50)),
                ('usage', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'HeavyVehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='motorcycle', serialize=False, to='vehicles.vehicle')),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=50, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_cc', models.IntegerField(blank=True, null=True)),
                ('gearbox', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Motorcycle',
                'managed': False,
            },
        ),
    ]
